### ISSUE TITLE
State lock/unlock isn't updatet

### ISSUE THREAD

**Issue by philsniff** [jordenc/io.nuki.smartlock#11] opened 2018-03-17 08:12 UTC
when i lock/unlock my doorlock with its own app or manual then the states in homey aren't updatet.
i would push a message to my phone when my daughter is coming home from school, but now i have to use ifttt for this. would be great if this can work without this workaround.

**Comment by chrisboer** [comment] 2018-03-17 09:17
Strange I don’t have this issue I will send you an picture of my flow

**Comment by philsniff** [comment] 2018-03-17 10:27
homey and nuki have static ips. and i restartet the nuki app, but nothing changed

**Comment by chrisboer** [comment] 2018-03-17 10:57
![afbeelding](https://user-images.githubusercontent.com/23163409/37554508-4e505d48-29da-11e8-8279-f85cff226ce8.png)

**Comment by chrisboer** [comment] 2018-03-17 11:01
Maybe it has something to do with the session, I had also an issue with this I will try to find the solution again on the forum

**Comment by philsniff** [comment] 2018-03-17 17:38
Would be Great @chris

**Comment by philsniff** [comment] 2018-03-18 16:15
i made all things that were reported in the forum. i now have only one entry when i call ...list?token=...

before there was not such en entry but after adding to the api from nuki it shows successfully only one line with id: 0 etc.

{"callbacks": [{"id": 0, "url": "192.168.xxx.xxx/api/app/io.nuki.smartlock/webhook"}]}

but still no update of the lock...

**Comment by jordenc** [comment] 2018-03-19 12:50
It works for me every time. You need, however, to use the cards of the app, not the status card of the lock. The last one doesn't work.
Same thing happens with the Danalock and it could be that the problem is with Homey, not the apps.

**Comment by philsniff** [comment] 2018-03-19 14:16
Ah ok, jorden. I will Test.

gruß

Am 19. März 2018, 13:50 +0100 schrieb Jorden <notifications@github.com>:

**Comment by philsniff** [comment] 2018-03-19 14:24
I can’t find the app in the flows section, only the device.

Or do i misunderstand something. Sorry then for that!

would you post me a screenshot of the working flow?

thats my card that i use: "laockstate changed"
![unbenannt](https://user-images.githubusercontent.com/7848863/37601108-80584ce6-2b89-11e8-84ed-58fd68a3a88c.PNG)

**Comment by jordenc** [comment] 2018-03-19 14:25
That's indeed the one that works:

![schermafbeelding 2018-03-19 om 15 20 20](https://user-images.githubusercontent.com/17727803/37601186-ad71347c-2b89-11e8-8a6f-35415ce42871.png)
It has never failed on me yet

**Comment by philsniff** [comment] 2018-03-19 14:27
Ok, thank you very much. But it works not for me.
there is ifttt so it is not sooo dramatically 😉

Gruß
Philipp Schnittger

Von: Jorden
Gesendet: Montag, 19. März 2018 15:25
An: jordenc/io.nuki.smartlock
Cc: philsniff; Author
Betreff: Re: [jordenc/io.nuki.smartlock] State lock/unlock isn't updatet (#11)

That's indeed the one that works:

It has never failed on me yet

**Comment by jordenc** [comment] 2018-03-19 14:50
Did you check if the Nuki has your Homey URL in the callback list?

http://<ip of nuki bridge>:8084/callback/list?token=<your token>

It should have something along the lines of:

http://192.168.2.20:80/api/app/io.nuki.smartlock/webhook

**Comment by philsniff** [comment] 2018-03-19 14:58
i added it as it was written somewhere in the forum thread.

therefor it was {"callbacks": []}

now it is {"callbacks": [{"id": 0, "url": "192.168.xxx.xxx/api/app/io.nuki.smartlock/webhook"}]}

so i think i did all right.
and it is only one line, so no other id which i have to remove...

 should i reboot homey perhaps?

**Comment by philsniff** [comment] 2018-03-19 14:59
there is no :80 behind my ulr... is this right?

**Comment by jordenc** [comment] 2018-03-20 08:44
OK then it didn't set the callback URL correctly, which means there indeed were no callbacks.

The URL should be correct even without :80 but I think it requires http:// in front. And did you make sure that 192.168.xxx.xxx is the correct, local IP of your Homey?

**Comment by philsniff** [comment] 2018-03-20 08:56
Hmm, i will try with http://...

Yes the static ip of my homey is correct for shure. I give all my devices in my wlan a static ip. And i looked up for homey.

No there must be another reason Then the ips.

I use chrome Webbrowser. There i only have to use the url without http, so i will try with.

But i don‘t think that this is the reason. ;-)

Greedings philipp

Am 20. März 2018, 09:44 +0100 schrieb Jorden <notifications@github.com>:

**Comment by jordenc** [comment] 2018-05-02 15:52
Fixed in 0.2.2! Submitted to the appstore for approval.

**Closed as completed by jordenc** 2018-05-02 15:52 UTC
